version: 2

project_name: agentduty

builds:
  - main: .
    binary: agentduty
    ldflags:
      - -s -w -X github.com/sestinj/agentduty/cli/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: sestinj
    name: agentduty
